baseUrl: "https://www.bavins.me"
languageCode: "en-us"
defaultContentLanguage: lv
title: "Vilhelms Bavins"
theme: "anubis"
paginate: 5

#disqusShortname: ""
#googleAnalytics: ""

languages:
  lv:
    languageName: Latviešu
    title: "Vilhelms Bavins"
  en:
    languageName: English
    title: "Vilhelms Bavins"
    menu:
      main:
      - identifier: archive
        name: Archive
        title: Archive
        url: /archive/
        weight: 1
      - identifier: tags
        name: Tags
        title: Tags
        url: /tags/
        weight: 2
      - identifier: about
        name: About / Contacts
        title: About / Contacts
        url: /about/
        weight: 3
#      - identifier: projects
#        name: Projects
#        title: Projects
#        url: /projects/
#        weight: 4
menu:
  main:
  - identifier: archive
    name: Arhīvs
    title: Arhīvs
    url: /archive/
    weight: 1
  - identifier: tags
    name: Tagi
    title: Tagi
    url: /tags/
    weight: 2
  - identifier: about
    name: Par sevi / Kontakti
    title: Par sevi / Kontakti
    url: /about/
    weight: 3
#  - identifier: projects
#    name: Projekti
#    title: Projekti
#    url: /projects/
#    weight: 4
    

params:
  author: "Vilhelms Bavins"
  description: "This is my personal website!"
  dateFormat: "02-01-2006"
  paginationSinglePost: true
  style: dark-without-switcher
  readMore: true
  readNextPosts: 2 
  disableSummary: false
  copyCodeButton: true
  rssAsSocialIcon: false
  # avatar: "/images/me.png"
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  
  # utteranc.es support // comments
  utterancesRepo: "https://github.com/villhelmms/website"  # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional

  social:
  - id: github
    name: villhelmms
  - id: instagram
    name: villhelmms
  - id: reddit
    name: villhelmms
  - id: spotify
    name: o613w1t5n87swodx9i6v0vpiq

taxonomies:
  category: categories
  tag: tags

markup:
  goldmark:
    renderer:
      unsafe: true